services:
  cmu_container:
    image: cmu_container
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    restart: always
    network_mode: "host"
    ipc: host
    environment:
      - ROS_DOMAIN_ID=0
      - FASTDDS_BUILTIN_TRANSPORTS=UDPv4
      - ROS_LOCALHOST_ONLY=0

