# controllers.yaml
controller_manager:
  ros__parameters:
    update_rate: 50                    # global update for all controllers
    # if you need use_sim_time: true

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    publish_rate: 50

diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ['front_left_wheel', 'back_left_wheel']
    right_wheel_names: ['front_right_wheel', 'back_right_wheel']
    publish_rate: 50
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    cmd_vel_timeout: 0.25
    velocity_rolling_window_size: 2
    base_frame_id: 'base_link'
    enable_odom_tf: false
    estimate_velocity_from_position: false

    wheel_separation_multiplier: 1.875
    wheel_radius_multiplier:     1.0

    linear_x:
      has_velocity_limits:    true
      max_velocity:           2.0
      has_acceleration_limits:true
      max_acceleration:       0.2

    angular_z:
      has_velocity_limits:    true
      max_velocity:           2.0
      has_acceleration_limits:true
      max_acceleration:       1.0
